using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Trasys.Dev.Tools.Data.Entity
{
    /// <summary>
    /// Description of a Column to manage (in UPDATE or INSERT commands).
    /// </summary>
    internal class ActionColumn
    {
        /// <summary>
        /// Gets the table name.
        /// </summary>
        public string TableName { get; internal set; }

        /// <summary>
        /// Gets the index number for this column.
        /// </summary>
        public int Index { get; internal set; }

        /// <summary>
        /// Gets the column name.
        /// </summary>
        public virtual string FieldName { get; internal set; }

        /// <summary>
        /// Gets the parameter name (@p[index]. Example: @p1, @p2, ...).
        /// </summary>
        public virtual string ParameterName { get; internal set; }

        /// <summary>
        /// Gets the value for this field.
        /// </summary>
        public virtual object Value { get; internal set; }

        /// <summary>
        /// Gets True if the property value has changed (and must be updated to the server).
        /// </summary>
        public bool IsValueChanged { get; internal set; }

        /// <summary>
        /// Gets True if this field is included in the Primary Key.
        /// </summary>
        public bool IsPrimaryKey { get; internal set; }

        /// <summary>
        /// Gets True if this field is auto-generate by the Server.
        /// </summary>
        public bool IsAutoGenerated { get; internal set; }

        /// <summary>
        /// Gets True if this field is auto-incremented by the Server.
        /// </summary>
        public bool IsIdentity { get; internal set; }

    }
}
